CREATE TABLE Superheroes (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	ALIAS VARCHAR(50) NOT NULL,
	ORIGIN TEXT NOT NULL 
);

CREATE TABLE Assistant (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Power (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description TEXT NOT NULL
);
